# Generated by Django 5.1.7 on 2025-03-19 08:41

import main.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to=main.services.file_upload_path),
        ),
    ]
